# -*- coding: utf-8 -*-
"""01_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyrzDAM7EYdJfX0YuDaJvadrO6--XPuv
"""

import warnings
warnings.filterwarnings("ignore") ## Dọn dẹp và làm sạch màn hình
import pandas as pd ## Thư viện đọc file dữ liệu
import numpy as np ## Thư viện tính toán
import seaborn as sns ## Vẽ các đồ thị
sns.set(style='darkgrid') ## Thiết lập kiểu đồ thị
import matplotlib.pyplot as plt ## Vẽ biểu đồ
import missingno as msno ## Trực quan hóa các giá trị bị thiếu
import os
import glob
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_recall_fscore_support
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
import xgboost as xgb
from xgboost import plot_importance

## Kết nối với hệ thống lưu trữ đám mây Google Drive
from google.colab import drive
drive.mount('/content/drive')
data1 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Monday-WorkingHours.pcap_ISCX.csv')
data2 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Tuesday-WorkingHours.pcap_ISCX.csv')
data3 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Wednesday-workingHours.pcap_ISCX.csv')
data4 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv')
data5 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv')
data6 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Friday-WorkingHours-Morning.pcap_ISCX.csv')
data7 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')
data8 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')

## Đọc kích thước của các file dữ liệu
data_list = [data1, data2, data3, data4, data5, data6, data7, data8]
print('Kích thước dữ liệu: ')
for i, data in enumerate(data_list, start = 1):
  rows, cols = data.shape
  print(f'Data{i} -> {rows} hàng, {cols} cột')

## Gộp và đọc các file dữ liệu
data = pd.concat(data_list)
rows, cols = data.shape
print('Kích thước dữ liệu:')
print(f'Số hàng: {rows}')
print(f'Số cột: {cols}')
print(f'Tổng số ô dữ liệu: {rows * cols}')

## Xóa các ô dữ liệu sau khi gộp để tiết kiệm bộ nhớ
for d in data_list: del d

## Đổi tên các cột bằng cách loại bỏ các khoảng trắng đầu cuối
col_names = {col: col.strip() for col in data.columns}
data.rename(columns = col_names, inplace = True)
data.columns

data.info()

pd.options.display.max_rows = 80
print('Tổng quan các cột dữ liệu:')
data.describe().transpose()

pd.options.display.max_columns = 80
data

## Tìm và đếm tổng số dòng dữ liệu bị trùng lặp
dups = data[data.duplicated()]
print(f'Số dòng trùng lặp: {len(dups)}')

## Xóa các dòng trùng lặp và in ra số hàng và cột sau khi xóa
data.drop_duplicates(inplace = True)
data.shape

data.reset_index(drop=True, inplace=True)
print('Chỉ mục đã được đặt lại.')

## Kiểm tra giá trị bị thiếu
missing_val = data.isna().sum()
print(missing_val.loc[missing_val > 0])

## Kiểm tra giá trị vô hạn
numeric_cols = data.select_dtypes(include = np.number).columns
inf_count = np.isinf(data[numeric_cols]).sum()
print(inf_count[inf_count > 0])

# Thay thế các giá trị vô hạn bằng NaN
print(f'Giá trị ban đầu bị thiếu: {data.isna().sum().sum()}')
data.replace([np.inf, -np.inf], np.nan, inplace = True)
print(f'Giá trị bị thiếu sau khi xử lý các giá trị vô hạn: {data.isna().sum().sum()}')

## Liệt kê các cột bị thiếu
missing = data.isna().sum()
print(missing.loc[missing > 0])

## Phần trăm giá trị bị thiếu trong dataset
mis_per = (missing / len(data)) * 100
mis_table = pd.concat([missing, mis_per.round(2)], axis = 1)
mis_table = mis_table.rename(columns = {0 : 'Giá trị thiếu', 1 : 'Phần trăm trong tổng số giá trị'})
print(mis_table.loc[mis_per > 0])

## Trực quan hóa dữ liệu bị thiếu
sns.set_palette('pastel')
colors = sns.color_palette()
missing_vals = [col for col in data.columns if data[col].isna().any()]
fig, ax = plt.subplots(figsize = (2, 6))
msno.bar(data[missing_vals], ax = ax, fontsize = 12, color = colors)
ax.set_xlabel('Đặc trưng', fontsize = 12)
ax.set_ylabel('Số giá trị rỗng', fontsize = 12)
ax.set_title('Biểu đồ giá trị bị thiếu', fontsize = 12)
plt.show()

## Xử lý giá trị bị thiếu
plt.figure(figsize = (8, 3))
sns.boxplot(x = data['Flow Bytes/s'])
plt.xlabel('Biểu đồ hộp của Flow Bytes/s')
plt.show()

colors = sns.color_palette('Blues')
plt.hist(data['Flow Bytes/s'], color = colors[1])
plt.title('Biểu đồ tần số của Flow Bytes/s')
plt.xlabel('Flow Bytes/s')
plt.ylabel('Tần số')
plt.show()

plt.figure(figsize = (8, 3))
sns.boxplot(x = data['Flow Packets/s'])
plt.xlabel('Biểu đồ hộp của Flow Packets/s')
plt.show()

plt.hist(data['Flow Packets/s'], color = colors[1])
plt.title('Biểu đồ tần số của Flow Packets/s')
plt.xlabel('Flow Packets/s')
plt.ylabel('Tần số')
plt.show()

med_flow_bytes = data['Flow Bytes/s'].median()
med_flow_packets = data['Flow Packets/s'].median()
print('Trung vị của Flow Bytes/s: ', med_flow_bytes)
print('Trung vị của Flow Packets/s: ', med_flow_packets)

## Điền các giá trị bị thiếu bằng trung vị
data['Flow Bytes/s'].fillna(med_flow_bytes, inplace = True)
data['Flow Packets/s'].fillna(med_flow_packets, inplace = True)

print('Số giá trị \'Flow Bytes/s\' bị thiếu:', data['Flow Bytes/s'].isna().sum())
print('Số giá trị \'Flow Packets/s\' bị thiếu:', data['Flow Packets/s'].isna().sum())

## Phân tích các mẫu dùng hình ảnh trực quan
data['Label'].unique()

## Các trường hợp tấn công và các trường hợp bình thường
data['Label'].value_counts()

## Tạo ánh xạ nhãn với loại tấn công tương ứng
attack_map = {
    'BENIGN': 'BENIGN',
    'DDoS': 'DDoS',
    'DoS Hulk': 'DoS',
    'DoS GoldenEye': 'DoS',
    'DoS slowloris': 'DoS',
    'DoS Slowhttptest': 'DoS',
    'PortScan': 'Port Scan',
    'FTP-Patator': 'Brute Force',
    'SSH-Patator': 'Brute Force',
    'Bot': 'Bot',
    'Web Attack � Brute Force': 'Web Attack',
    'Web Attack � XSS': 'Web Attack',
    'Web Attack � Sql Injection': 'Web Attack',
    'Infiltration': 'Infiltration',
    'Heartbleed': 'Heartbleed'
}

## Tạo một cột mới 'Attack Type' trong DataFrame dựa trên từ điển attack_map
data['Attack Type'] = data['Label'].map(attack_map)

data['Attack Type'].value_counts()

## Xóa bớt để giảm bớt dữ liệu
data.drop('Label', axis = 1, inplace = True)

## Mã hóa nhãn
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Attack Number'] = le.fit_transform(data['Attack Type'])
print(data['Attack Number'].unique())
## In ra loại tấn công tương ứng cho mỗi giá trị được mã hóa
encoded_values = data['Attack Number'].unique()
for val in sorted(encoded_values):
    print(f"{val}: {le.inverse_transform([val])[0]}")

## Tính toán và hiển thị ma trận tương quan
corr = data.corr(numeric_only = True).round(2)
corr.style.background_gradient(cmap = 'coolwarm', axis = None).format(precision = 2)

## Vẽ biểu đồ nhiệt cho ma trận tương quan
fig, ax = plt.subplots(figsize = (24, 24))
sns.heatmap(corr, cmap = 'coolwarm', annot = False, linewidth = 0.5)
plt.title('Ma trận tương quan', fontsize = 18)
plt.show()

## Các đặc điểm tương quan tích cực đối với 'Attack Number'
pos_corr_features = corr['Attack Number'][(corr['Attack Number'] > 0) & (corr['Attack Number'] < 1)].index.tolist()

print("Đặc điểm tương quan với 'Attack Number':\n")
for i, feature in enumerate(pos_corr_features, start = 1):
    corr_value = corr.loc[feature, 'Attack Number']
    print('{:<3} {:<24} :{}'.format(f'{i}.', feature, corr_value))

print(f'Số lượng đặc trưng quan trọng đáng kể: {len(pos_corr_features)}')

## Kiểm tra các cột có độ lệch chuẩn bằng 0
std = data.std(numeric_only = True)
zero_std_cols = std[std == 0].index.tolist()
zero_std_cols

## Lấy mẫu 20% dữ liệu để thực hiện phân tích nhanh hơn
sample_size = int(0.2 * len(data))
sampled_data = data.sample(n = sample_size, replace = False, random_state = 0)
print(f'Kích thước dữ liệu gốc: {data.shape}')
print(f'Kích thước dữ liệu sau khi lấy mẫu (20%): {sampled_data.shape}')

# So sánh thống kê mô tả (giá trị trung bình) để đánh giá tính đại diện của tập mẫu
numeric_cols = data.select_dtypes(include = [np.number]).columns.tolist()
print('So sánh thống kê mô tả (Mean):\n')
print('{:<32s}{:<22s}{:<22s}{}'.format('Feature', 'Original Dataset', 'Sampled Dataset', 'Variation Percentage'))
print('-' * 96)
high_variations = []
for col in numeric_cols:
    old = data[col].mean()
    new = sampled_data[col].mean()
    if old == 0:
        pct = 0
    else:
        pct = abs((new - old) / old)
    if pct * 100 > 5:
        high_variations.append((col, pct * 100))
    print('{:<32s}{:<22.6f}{:<22.6f}{:<2.2%}'.format(col, old, new, pct))

## Trực quan hóa các đặc trưng có mức độ sai lệch trung bình > 5%
labels = [t[0] for t in high_variations]
values = [t[1] for t in high_variations]
if labels:
    colors = sns.color_palette('Blues_r', n_colors=len(labels))
    fig, ax = plt.subplots(figsize = (12, 6))
    ax.bar(labels, values, color = colors)
    for i in range(len(labels)):
        ax.text(i, values[i], f'{round(values[i], 2)}%', ha = 'center', va = 'bottom', fontsize = 10)
    plt.xticks(rotation = 90)
    ax.set_title('Các đặc trưng có sai lệch giá trị trung bình > 5% so với tập gốc')
    ax.set_ylabel('Phần trăm sai lệch (%)')
    ax.set_yticks(np.arange(0, max(values) + 10, 5))
    plt.tight_layout()
    plt.show()
else:
    print('Không có đặc trưng nào có sai lệch lớn hơn 5%. Tập mẫu rất đại diện!')

## In số lượng giá trị duy nhất của từng đặc trưng
indent = '{:<3} {:<30}: {}'
print('Số lượng giá trị duy nhất cho từng cột:')
## Lặp qua các cột ngoại trừ cột cuối cùng (Attack Number/Attack Type)
for i, feature in enumerate(list(sampled_data.columns)[:-1], start = 1):
    print(indent.format(f'{i}.', feature, sampled_data[feature].nunique()))

## Tạo biểu đồ cho các cột có từ 2 đến 50 giá trị duy nhất
unique_values = sampled_data.nunique()
selected_cols = sampled_data[[col for col in sampled_data if 1 < unique_values[col] < 50]]
rows, cols = selected_cols.shape
col_names = list(selected_cols)
num_of_rows = (cols + 3) // 4
color_palette = sns.color_palette('Blues', n_colors = 3)
plt.figure(figsize = (24, 8 * num_of_rows))
for i in range(cols):
    plt.subplot(num_of_rows, 4, i + 1)
    col_data = selected_cols.iloc[:, i]
    if col_data.dtype.name == 'object':
        col_data.value_counts().plot(kind = 'bar', color = color_palette[2])
    else:
        col_data.hist(color = color_palette[0])
    plt.ylabel('Tần suất')
    plt.xticks(rotation = 45)
    plt.title(col_names[i])

plt.tight_layout()
plt.show()

## Ma trận tương quan cho dữ liệu mẫu
corr_matrix = sampled_data.corr(numeric_only = True).round(2)
corr_matrix.style.background_gradient(cmap = 'coolwarm', axis = None).format(precision = 2)

## Vẽ biểu đồ cho các cặp đặc trưng có tương quan thuận mạnh (>= 0.85)
cols = [col for col in sampled_data.columns if col not in ['Attack Type', 'Attack Number']]
high_corr_pairs = []
corr_th = 0.85
for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        val = sampled_data[cols[i]].corr(sampled_data[cols[j]])
        if np.isnan(val) or val < corr_th:
            continue
        high_corr_pairs.append((val, cols[i], cols[j]))
size = len(high_corr_pairs)
num_cols = 4
num_rows = (size + num_cols - 1) // num_cols
if size > 0:
    fig, axs = plt.subplots(num_rows, num_cols, figsize = (24, num_rows * 5))
    if num_rows == 1:
        axs = axs.reshape(1, -1)
    for i in range(num_rows):
        for j in range(num_cols):
            idx = i * num_cols + j
            if idx < size:
                val, x, y = high_corr_pairs[idx]
                color = 'green' if val > 0.99 else 'blue'
                axs[i, j].scatter(sampled_data[x], sampled_data[y], color = color, alpha = 0.1)
                axs[i, j].set_xlabel(x)
                axs[i, j].set_ylabel(y)
                axs[i, j].set_title(f'{x} vs\n{y} ({val:.2f})')
            else:
                fig.delaxes(axs[i, j])
    fig.tight_layout()
    plt.show()
else:
    print('Không tìm thấy cặp đặc trưng nào có tương quan >= 0.85')

## Loại bỏ cột 'Attack Number' khỏi dữ liệu gốc và dữ liệu mẫu
sampled_data.drop('Attack Number', axis = 1, inplace = True)
data.drop('Attack Number', axis = 1, inplace = True)
print('Đã loại bỏ cột Attack Number.')

## Nhận diện các giá trị ngoại lệ (outliers) bằng phương pháp IQR
numeric_data = sampled_data.select_dtypes(include = ['float', 'int'])
q1 = numeric_data.quantile(0.25)
q3 = numeric_data.quantile(0.75)
iqr = q3 - q1
outlier = (numeric_data < (q1 - 1.5 * iqr)) | (numeric_data > (q3 + 1.5 * iqr))
outlier_count = outlier.sum()
outlier_percentage = round(outlier.mean() * 100, 2)
outlier_stats = pd.concat([outlier_count, outlier_percentage], axis = 1)
outlier_stats.columns = ['Số lượng Outliers', 'Tỷ lệ % Outliers']
## Hiển thị các cột có outlier
display(outlier_stats[outlier_stats['Số lượng Outliers'] > 0])

## Nhận diện giá trị ngoại lệ dựa trên từng loại tấn công
outlier_counts = {}
for i in numeric_data:
    for attack_type in sampled_data['Attack Type'].unique():
        attack_data = sampled_data[i][sampled_data['Attack Type'] == attack_type]
        q1, q3 = np.percentile(attack_data, [25, 75])
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        num_outliers = ((attack_data < lower_bound) | (attack_data > upper_bound)).sum()
        outlier_percent = num_outliers / len(attack_data) * 100
        outlier_counts[(i, attack_type)] = (num_outliers, outlier_percent)

for i in numeric_data:
  print(f'Feature: {i}')
  for attack_type in sampled_data['Attack Type'].unique():
    num_outliers, outlier_percent = outlier_counts[(i, attack_type)]
    print(f'- {attack_type}: {num_outliers} ({outlier_percent:.2f}%)')
  print()

## Trực quan hóa phần trăm giá trị ngoại lệ lớn hơn 20%
fig, ax = plt.subplots(figsize = (24, 10))
for i in numeric_data:
    for attack_type in sampled_data['Attack Type'].unique():
        num_outliers, outlier_percent = outlier_counts[(i, attack_type)]
        if outlier_percent > 20:
            ax.bar(f'{i} - {attack_type}', outlier_percent)

ax.set_xlabel('Feature-Attack Type')
ax.set_ylabel('Percentage of Outliers')
ax.set_title('Outlier Analysis')
ax.set_yticks(np.arange(0, 41, 10))
plt.xticks(rotation = 90)
plt.show()

## Trực quan hóa mối quan hệ giữa các cột
## Phân phối các loại tấn công trong tập dữ liệu chính (loại trừ 'BENIGN')
attacks = data.loc[data['Attack Type'] != 'BENIGN']

plt.figure(figsize = (10, 6))
ax = sns.countplot(x = 'Attack Type', data = attacks, palette = 'pastel', order = attacks['Attack Type'].value_counts().index)
plt.title('Số lượng các loại tấn công')
plt.xlabel('Loại tấn công')
plt.ylabel('Số lượng mẫu')
plt.xticks(rotation = 90)

for p in ax.patches:
    ax.annotate(f'{p.get_height():.0f}', (p.get_x() + p.get_width() / 2, p.get_height() + 1000), ha = 'center')

plt.show()

## Trực quan hóa tỷ lệ phần trăm các loại tấn công bằng biểu đồ tròn
attack_counts = attacks['Attack Type'].value_counts()
threshold = 0.005
percentages = attack_counts / attack_counts.sum()
# Gộp các loại tấn công nhỏ vào nhóm 'Other'
small_slices = percentages[percentages < threshold].index.tolist()
attack_counts['Other'] = attack_counts[small_slices].sum()
attack_counts.drop(small_slices, inplace = True)
# Vẽ biểu đồ
sns.set_palette('pastel')
plt.figure(figsize = (8, 8))
plt.pie(attack_counts.values, labels = attack_counts.index, autopct = '%1.1f%%', startangle=140, textprops={'fontsize': 10})
plt.title('Tỷ lệ phân bổ các loại hình tấn công', fontsize=14)
plt.legend(attack_counts.index, loc = 'best')
plt.show()

## Tạo biểu đồ hộp cho mỗi loại tấn công để quan sát phân phối đặc trưng
for attack_type in sampled_data['Attack Type'].unique():
    attack_data = sampled_data[sampled_data['Attack Type'] == attack_type]
    plt.figure(figsize=(25, 25))
    # Loại bỏ cột phân loại để chỉ vẽ các cột số
    sns.boxplot(data = attack_data.drop(columns = ['Attack Type']), orient = 'h')
    plt.title(f'Biểu đồ hộp các đặc trưng cho loại tấn công: {attack_type}')
    plt.xlabel('Giá trị đặc trưng')
    plt.tight_layout()
    plt.show()

## Xem dòng dữ liệu đầu tiên của mỗi loại tấn công
display(data.groupby('Attack Type').first())

## Tối ưu hóa bộ nhớ bằng cách Downcasting kiểu dữ liệu số
old_memory_usage = data.memory_usage().sum() / 1024 ** 2
print(f'Bộ nhớ tiêu thụ ban đầu: {old_memory_usage:.2f} MB')
for col in data.columns:
    col_type = data[col].dtype
    if col_type != object:
        c_min = data[col].min()
        c_max = data[col].max()
        # Downcasting float64 sang float32
        if str(col_type).find('float') >= 0 and c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
            data[col] = data[col].astype(np.float32)
        # Downcasting int64 sang int32
        elif str(col_type).find('int') >= 0 and c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
            data[col] = data[col].astype(np.int32)

new_memory_usage = data.memory_usage().sum() / 1024 ** 2
print(f'Bộ nhớ tiêu thụ sau khi tối ưu: {new_memory_usage:.2f} MB')
print(f'Đã giảm được: {((old_memory_usage - new_memory_usage) / old_memory_usage) * 100:.2f}%')

data.info()

data.describe().transpose()

## Loại bỏ các cột chỉ có duy nhất một giá trị (biến hằng số)
num_unique = data.nunique()
one_variable = num_unique[num_unique == 1]
not_one_variable = num_unique[num_unique > 1].index

dropped_cols = one_variable.index
data = data[not_one_variable]

print('Các cột đã gộp:')
dropped_cols

data.shape

## Hiển thị danh sách các cột còn lại sau khi lọc
print(f'Số lượng cột còn lại: {len(data.columns)}')
data.columns

data

# Đường dẫn lưu file
export_path = '/content/drive/MyDrive/BTL_TSL_MR/cleaned_data.csv'
# Lưu DataFrame thành CSV (loại bỏ index để file nhẹ hơn)
data.to_csv(export_path, index=False)
print(f'Đã lưu dữ liệu thành công tại: {export_path}')

data_cleaned = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/cleaned_data.csv')
rows, cols = data_cleaned.shape
print('Kích thước dữ liệu:')
print(f'Số hàng: {rows}')
print(f'Số cột: {cols}')
print(f'Tổng số ô dữ liệu: {rows * cols}')