# -*- coding: utf-8 -*-
"""01_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyrzDAM7EYdJfX0YuDaJvadrO6--XPuv
"""

import warnings
warnings.filterwarnings("ignore") ## Dọn dẹp và làm sạch màn hình
import pandas as pd ## Thư viện đọc file dữ liệu
import numpy as np ## Thư viện tính toán
import seaborn as sns ## Vẽ các đồ thị
sns.set(style='darkgrid') ## Thiết lập kiểu đồ thị
import matplotlib.pyplot as plt ## Vẽ biểu đồ
import missingno as msno ## Trực quan hóa các giá trị bị thiếu
import os
import glob
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_recall_fscore_support
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
import xgboost as xgb
from xgboost import plot_importance

## Kết nối với hệ thống lưu trữ đám mây Google Drive
from google.colab import drive
drive.mount('/content/drive')
data1 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Monday-WorkingHours.pcap_ISCX.csv')
data2 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Tuesday-WorkingHours.pcap_ISCX.csv')
data3 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Wednesday-workingHours.pcap_ISCX.csv')
data4 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv')
data5 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv')
data6 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Friday-WorkingHours-Morning.pcap_ISCX.csv')
data7 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')
data8 = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')

## Đọc kích thước của các file dữ liệu
data_list = [data1, data2, data3, data4, data5, data6, data7, data8]
print('Kích thước dữ liệu: ')
for i, data in enumerate(data_list, start = 1):
  rows, cols = data.shape
  print(f'Data{i} -> {rows} hàng, {cols} cột')

## Gộp và đọc các file dữ liệu
data = pd.concat(data_list)
rows, cols = data.shape
print('Kích thước dữ liệu:')
print(f'Số hàng: {rows}')
print(f'Số cột: {cols}')
print(f'Tổng số ô dữ liệu: {rows * cols}')

## Xóa các ô dữ liệu sau khi gộp để tiết kiệm bộ nhớ
for d in data_list: del d

## Đổi tên các cột bằng cách loại bỏ các khoảng trắng đầu cuối
col_names = {col: col.strip() for col in data.columns}
data.rename(columns = col_names, inplace = True)
data.columns

data.info()

## Tìm và đếm tổng số dòng dữ liệu bị trùng lặp
dups = data[data.duplicated()]
print(f'Số dòng trùng lặp: {len(dups)}')

## Xóa các dòng trùng lặp và in ra số hàng và cột sau khi xóa
data.drop_duplicates(inplace = True)
data.shape

data.reset_index(drop=True, inplace=True)
print('Chỉ mục đã được đặt lại.')

## Kiểm tra giá trị bị thiếu
missing_val = data.isna().sum()
print(missing_val.loc[missing_val > 0])

## Kiểm tra giá trị vô hạn
numeric_cols = data.select_dtypes(include = np.number).columns
inf_count = np.isinf(data[numeric_cols]).sum()
print(inf_count[inf_count > 0])

# Thay thế các giá trị vô hạn bằng NaN
print(f'Giá trị ban đầu bị thiếu: {data.isna().sum().sum()}')
data.replace([np.inf, -np.inf], np.nan, inplace = True)
print(f'Giá trị bị thiếu sau khi xử lý các giá trị vô hạn: {data.isna().sum().sum()}')

## Liệt kê các cột bị thiếu
missing = data.isna().sum()
print(missing.loc[missing > 0])

## Phần trăm giá trị bị thiếu trong dataset
mis_per = (missing / len(data)) * 100
mis_table = pd.concat([missing, mis_per.round(2)], axis = 1)
mis_table = mis_table.rename(columns = {0 : 'Giá trị thiếu', 1 : 'Phần trăm trong tổng số giá trị'})
print(mis_table.loc[mis_per > 0])

med_flow_bytes = data['Flow Bytes/s'].median()
med_flow_packets = data['Flow Packets/s'].median()
print('Trung vị của Flow Bytes/s: ', med_flow_bytes)
print('Trung vị của Flow Packets/s: ', med_flow_packets)

## Điền các giá trị bị thiếu bằng trung vị
data['Flow Bytes/s'].fillna(med_flow_bytes, inplace = True)
data['Flow Packets/s'].fillna(med_flow_packets, inplace = True)

print('Số giá trị \'Flow Bytes/s\' bị thiếu:', data['Flow Bytes/s'].isna().sum())
print('Số giá trị \'Flow Packets/s\' bị thiếu:', data['Flow Packets/s'].isna().sum())

## Phân tích các mẫu dùng hình ảnh trực quan
data['Label'].unique()

## Các trường hợp tấn công và các trường hợp bình thường
data['Label'].value_counts()

## Tạo ánh xạ nhãn với loại tấn công tương ứng
attack_map = {
    'BENIGN': 'BENIGN',
    'DDoS': 'DDoS',
    'DoS Hulk': 'DoS',
    'DoS GoldenEye': 'DoS',
    'DoS slowloris': 'DoS',
    'DoS Slowhttptest': 'DoS',
    'PortScan': 'Port Scan',
    'FTP-Patator': 'Brute Force',
    'SSH-Patator': 'Brute Force',
    'Bot': 'Bot',
    'Web Attack � Brute Force': 'Web Attack',
    'Web Attack � XSS': 'Web Attack',
    'Web Attack � Sql Injection': 'Web Attack',
    'Infiltration': 'Infiltration',
    'Heartbleed': 'Heartbleed'
}

## Tạo một cột mới 'Attack Type' trong DataFrame dựa trên từ điển attack_map
data['Attack Type'] = data['Label'].map(attack_map)

data['Attack Type'].value_counts()

## Xóa bớt để giảm bớt dữ liệu
data.drop('Label', axis = 1, inplace = True)

## Mã hóa nhãn
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Attack Number'] = le.fit_transform(data['Attack Type'])
print(data['Attack Number'].unique())
## In ra loại tấn công tương ứng cho mỗi giá trị được mã hóa
encoded_values = data['Attack Number'].unique()
for val in sorted(encoded_values):
    print(f"{val}: {le.inverse_transform([val])[0]}")

## Tính toán và hiển thị ma trận tương quan
corr = data.corr(numeric_only = True).round(2)
corr.style.background_gradient(cmap = 'coolwarm', axis = None).format(precision = 2)

## Các đặc điểm tương quan tích cực đối với 'Attack Number'
pos_corr_features = corr['Attack Number'][(corr['Attack Number'] > 0) & (corr['Attack Number'] < 1)].index.tolist()

print("Đặc điểm tương quan với 'Attack Number':\n")
for i, feature in enumerate(pos_corr_features, start = 1):
    corr_value = corr.loc[feature, 'Attack Number']
    print('{:<3} {:<24} :{}'.format(f'{i}.', feature, corr_value))

print(f'Số lượng đặc trưng quan trọng đáng kể: {len(pos_corr_features)}')

## Kiểm tra các cột có độ lệch chuẩn bằng 0
std = data.std(numeric_only = True)
zero_std_cols = std[std == 0].index.tolist()
zero_std_cols

## Lấy mẫu 20% dữ liệu để thực hiện phân tích nhanh hơn
sample_size = int(0.2 * len(data))
sampled_data = data.sample(n = sample_size, replace = False, random_state = 0)
print(f'Kích thước dữ liệu gốc: {data.shape}')
print(f'Kích thước dữ liệu sau khi lấy mẫu (20%): {sampled_data.shape}')

## In số lượng giá trị duy nhất của từng đặc trưng
indent = '{:<3} {:<30}: {}'
print('Số lượng giá trị duy nhất cho từng cột:')
## Lặp qua các cột ngoại trừ cột cuối cùng (Attack Number/Attack Type)
for i, feature in enumerate(list(sampled_data.columns)[:-1], start = 1):
    print(indent.format(f'{i}.', feature, sampled_data[feature].nunique()))

## Loại bỏ cột 'Attack Number' khỏi dữ liệu gốc và dữ liệu mẫu
sampled_data.drop('Attack Number', axis = 1, inplace = True)
data.drop('Attack Number', axis = 1, inplace = True)
print('Đã loại bỏ cột Attack Number.')

## Trực quan hóa mối quan hệ giữa các cột
## Phân phối các loại tấn công trong tập dữ liệu chính (loại trừ 'BENIGN')
attacks = data.loc[data['Attack Type'] != 'BENIGN']

plt.figure(figsize = (10, 6))
ax = sns.countplot(x = 'Attack Type', data = attacks, palette = 'pastel', order = attacks['Attack Type'].value_counts().index)
plt.title('Số lượng các loại tấn công')
plt.xlabel('Loại tấn công')
plt.ylabel('Số lượng mẫu')
plt.xticks(rotation = 90)

for p in ax.patches:
    ax.annotate(f'{p.get_height():.0f}', (p.get_x() + p.get_width() / 2, p.get_height() + 1000), ha = 'center')

plt.show()

## Tối ưu hóa bộ nhớ bằng cách Downcasting kiểu dữ liệu số
old_memory_usage = data.memory_usage().sum() / 1024 ** 2
print(f'Bộ nhớ tiêu thụ ban đầu: {old_memory_usage:.2f} MB')
for col in data.columns:
    col_type = data[col].dtype
    if col_type != object:
        c_min = data[col].min()
        c_max = data[col].max()
        # Downcasting float64 sang float32
        if str(col_type).find('float') >= 0 and c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
            data[col] = data[col].astype(np.float32)
        # Downcasting int64 sang int32
        elif str(col_type).find('int') >= 0 and c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
            data[col] = data[col].astype(np.int32)

new_memory_usage = data.memory_usage().sum() / 1024 ** 2
print(f'Bộ nhớ tiêu thụ sau khi tối ưu: {new_memory_usage:.2f} MB')
print(f'Đã giảm được: {((old_memory_usage - new_memory_usage) / old_memory_usage) * 100:.2f}%')

data.info()

## Loại bỏ các cột chỉ có duy nhất một giá trị (biến hằng số)
num_unique = data.nunique()
one_variable = num_unique[num_unique == 1]
not_one_variable = num_unique[num_unique > 1].index

dropped_cols = one_variable.index
data = data[not_one_variable]

print('Các cột đã gộp:')
dropped_cols

data.shape

## Hiển thị danh sách các cột còn lại sau khi lọc
print(f'Số lượng cột còn lại: {len(data.columns)}')
data.columns

# Đường dẫn lưu file
export_path = '/content/drive/MyDrive/BTL_TSL_MR/cleaned_data.csv'
# Lưu DataFrame thành CSV (loại bỏ index để file nhẹ hơn)
data.to_csv(export_path, index=False)
print(f'Đã lưu dữ liệu thành công tại: {export_path}')

data_cleaned = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/cleaned_data.csv')
rows, cols = data_cleaned.shape
print('Kích thước dữ liệu:')
print(f'Số hàng: {rows}')
print(f'Số cột: {cols}')
print(f'Tổng số ô dữ liệu: {rows * cols}')