# -*- coding: utf-8 -*-
"""02_Feature_Selection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1cDgr4iW0ovrmnhwBjXz4yr6mkfEXoa
"""

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings("ignore") ## Dọn dẹp và làm sạch màn hình
import pandas as pd ## Thư viện đọc file dữ liệu
import numpy as np ## Thư viện tính toán
import seaborn as sns ## Vẽ các đồ thị
sns.set(style='darkgrid') ## Thiết lập kiểu đồ thị
import matplotlib.pyplot as plt ## Vẽ biểu đồ
# %matplotlib inline
import missingno as msno ## Trực quan hóa các giá trị bị thiếu
import os
import glob
import sklearn as sk
import time
seconds = time.time()
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_recall_fscore_support
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
import xgboost as xgb
from xgboost import plot_importance

from google.colab import drive
drive.mount('/content/drive')

## Đọc dữ liệu từ file đã làm sạch
file_path = '/content/drive/MyDrive/BTL_TSL_MR/cleaned_data.csv'
df = pd.read_csv(file_path)
print(f"Đã load xong dữ liệu với kích thước: {df.shape}")

## Đổi Nhãn (BENIGN -> 0, Attack -> 1)
label_column_name = df.columns[-1]
df[label_column_name] = df[label_column_name].apply(lambda x: 0 if x == "BENIGN" else 1)
y = df[label_column_name].values
X = df.drop(columns=[label_column_name])
feature_names = X.columns

## Huấn luyện AI để lọc đặc trưng bằng Random
start_time = time.time()
forest = RandomForestClassifier(n_estimators=50, random_state=42, n_jobs=-1)
forest.fit(X, y)
print(f"Huấn luyện xong trong: {round((time.time() - start_time)/60, 2)} phút")

## Trích xuất điểm số từ mô hình đã huấn luyện
importances = forest.feature_importances_
feature_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
## Lấy 20 đặc trưng có điểm cao nhất
top_20_features = feature_df.sort_values(by='Importance', ascending=False).head(20)
print(top_20_features.reset_index(drop=True))
## Vẽ biểu đồ
plt.figure(figsize=(14, 7))
plt.bar(top_20_features['Feature'], top_20_features['Importance'], color='coral', edgecolor='black')
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.title('Top 20 thông số mạng quan trọng nhất để phát hiện tấn công', fontsize=14, fontweight='bold')
plt.ylabel('Mức độ quan trọng', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

## Lấy danh sách tên của 20 cột tốt nhất
best_features_list = top_20_features['Feature'].tolist()
## Tạo dataframe mới chỉ chứa 20 cột này và cột Nhãn cuối cùng
df_optimal = df[best_features_list + [label_column_name]]
# Đường dẫn lưu file
optimal_path = '/content/drive/MyDrive/BTL_TSL_MR/optimal_data.csv'
df_optimal.to_csv(optimal_path, index=False)
print(f"Lưu thành công tập dữ liệu tối ưu (chỉ còn {df_optimal.shape[1]} cột) tại: {optimal_path}")