# -*- coding: utf-8 -*-
"""04_Model_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ETuPg-YJCjlykOl7nCcnqS5w-6yqfxhd
"""

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings("ignore") ## Dọn dẹp và làm sạch màn hình
import pandas as pd ## Thư viện đọc file dữ liệu
import numpy as np ## Thư viện tính toán
import seaborn as sns ## Vẽ các đồ thị
sns.set(style='darkgrid') ## Thiết lập kiểu đồ thị
import matplotlib.pyplot as plt ## Vẽ biểu đồ
# %matplotlib inline
import missingno as msno ## Trực quan hóa các giá trị bị thiếu
import os
import glob
import sklearn as sk
import time
seconds = time.time()
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_recall_fscore_support, precision_score, recall_score
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
import xgboost as xgb
from xgboost import plot_importance
import joblib

from google.colab import drive
drive.mount('/content/drive')

## Load dữ liệu chuẩn bị train
train_df = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/train_smote_data.csv')
test_df = pd.read_csv('/content/drive/MyDrive/BTL_TSL_MR/test_data.csv')
X_train = train_df.drop(columns=[train_df.columns[-1]])
y_train = train_df[train_df.columns[-1]]
X_test = test_df.drop(columns=[test_df.columns[-1]])
y_test = test_df[test_df.columns[-1]]
print(f"Sẵn sàng huấn luyện với {X_train.shape[0]} mẫu cân bằng!")

## Khai báo các model train
models = {
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    "Extra Trees": ExtraTreesClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    "XGBoost": xgb.XGBClassifier(n_estimators=100, random_state=42, n_jobs=-1, tree_method='hist'),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42, n_jobs=-1),
    "Naive Bayes": GaussianNB()
}

## Bắt đầu huấn luyện và so sánh kết quả 6 mô hình với nhau
## Tạo một danh sách rỗng để lưu kết quả chấm điểm
results = []
for name, model in models.items():
    print(f"\nĐang train mô hình: {name}...")
    start_time = time.time()
    ## Học trên tập Train
    model.fit(X_train, y_train)
    train_time = round(time.time() - start_time, 2)
    ## Làm bài thi trên tập Test
    y_pred = model.predict(X_test)
    ## Chấm điểm
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    precision_weighted = precision_score(y_test, y_pred, average='weighted')
    recall_weighted = recall_score(y_test, y_pred, average='weighted')
    print(f"Thời gian train: {train_time}s | Accuracy: {acc*100:.2f}% | F1-Score: {f1*100:.2f}% | Precision: {precision_weighted*100:.2f}% | Recall: {recall_weighted*100:.2f}%")
    ## Lưu bảng điểm vào danh sách
    results.append({
        "Model": name,
        "Accuracy (%)": acc * 100,
        "F1-Score (%)": f1 * 100,
        "Precision (%)": precision_weighted * 100,
        "Recall (%)": recall_weighted * 100,
        "Train Time (s)": train_time
    })

## Lập bảng và vẽ biểu đồ
## Biến danh sách kết quả thành bảng DataFrame
results_df = pd.DataFrame(results)
print(results_df.to_markdown(index=False))
## Vẽ biểu đồ cột so sánh điểm F1-Score
plt.figure(figsize=(12, 6))
## Dùng hue và legend=False để tránh cảnh báo của Seaborn bản mới
sns.barplot(x='Model', y='F1-Score (%)', data=results_df, hue='Model', palette='viridis', legend=False)
## Gắn con số phần trăm lên đỉnh từng cột cho đẹp
for index, row in results_df.iterrows():
    plt.text(index, row['F1-Score (%)'] + 1, f"{row['F1-Score (%)']:.2f}%", color='black', ha="center", fontweight='bold')
plt.ylim(0, 115)
plt.title('So sánh hiệu suất phát hiện tấn công của các mô hình', fontsize=14, fontweight='bold')
plt.ylabel('F1-Score (%)', fontsize=12)
plt.xlabel('Thuật toán Machine Learning', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

## Đóng gói mô hình
best_model = models["XGBoost"]
model_path = '/content/drive/MyDrive/BTL_TSL_MR/Best_Model_Final.pkl'
joblib.dump(best_model, model_path)
print(f"XUẤT MODEL THÀNH CÔNG!")
print(f"File AI để nhúng vào OpenNMS đang nằm tại: {model_path}")

import joblib
model = joblib.load('/content/drive/MyDrive/BTL_TSL_MR/Best_Model_Final.pkl')
# Nếu là XGBoost, nó thường lưu tên feature trong attribute này:
print(model.get_booster().feature_names)